<a href="https://colab.research.google.com/github/Tojiyevvd/SI/blob/main/10_Topshiriq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#tasodifiy raqamlarni hosil qlish
#xosilbolgan raqam 0 va 1 oraliqda chiqadi
a=np.random.rand()
print(a)

0.967780879652862


In [ ]:
kop2=np.random.rand(5,3)
print(kop2*1000)

[[242.05197063  53.32687325 895.27969764]
 [411.92971602 928.65843546 624.37882152]
 [914.84844191 434.02411672 341.83256678]
 [614.18330118 713.12851675 300.27460093]
 [746.77423376 879.46403984 163.98157137]]


In [ ]:
kop3=np.random.rand(4,2,3)
print(kop3)

[[[0.45639319 0.86976219 0.39759495]
  [0.72401189 0.63736699 0.92505227]]

 [[0.40031105 0.98865271 0.81523751]
  [0.142096   0.33743006 0.59800717]]

 [[0.84365431 0.30789924 0.44506844]
  [0.6237643  0.83654586 0.82656701]]

 [[0.02184225 0.55317269 0.57854162]
  [0.33238697 0.45424927 0.24751788]]]


In [ ]:
oddiy=np.random.randint(1,17) #tasodifiy raqam olib beradi wular oraligida
print(oddiy)

6


In [ ]:
oddiy2=np.random.randint(1,100,size=10)
print(oddiy2)

[12 40 94 17 28 12 58  6 13 33]


In [ ]:
oddiy3=np.random.randint(1,100,size=(3,3))#2olchovli masiv yaratdik
print(oddiy3)

[[53 94 45]
 [ 5 29 59]
 [73 14 36]]


In [ ]:
oddiy4=np.random.randint(1,100,size=(3,4,5))
print(oddiy4)#3 olchovli massiv

[[[39 24 80  7  6]
  [45 54 59 66 82]
  [44 86 41 48 18]
  [38 12 75 73 51]]

 [[68 67 62  3 40]
  [24 22  8 74 90]
  [ 8 64 62 56 51]
  [59 99 54  1 20]]

 [[30 87 46 38 88]
  [31 15 53 30 81]
  [ 9 89 37 20 51]
  [35  8 55 87 53]]]


In [ ]:
#Tanlov=choice
list=[10,20,30,40,50,60,70,80,90,100]
tanlov=np.random.choice(list)
print(tanlov)

40


In [ ]:
#6ta soni tanlab beradi kritilgan raqmlar ichidan
list=[10,20,30,40,50,60,70,80,90,100]
koptanlov=np.random.choice(list,size=6,replace=False)
print(koptanlov)
#false sonlardi qayta qayta omedi
#true ikkita qlb oladi

[ 50  70  40 100  10  30]


In [ ]:
a=np.random.rand(8)
print(a)

[0.7382544  0.95253417 0.51012477 0.40455995 0.67813352 0.86389789
 0.60128776 0.42073024]


In [ ]:
np.random.seed(42)
r=np.random.rand(10)
print(r)
#seed=tasodifiy raqamdi qotirib beradi

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]


In [ ]:
#suffle=azratish
arr=np.array([1,2,3,4,5,6,7])
np.random.shuffle(arr)
print(arr)

[1 3 7 4 2 5 6]


In [ ]:
#vazifa

In [ ]:
bir=np.random.randint(1,100,size=(3))#1olchovli masiv yaratdik
print(bir*10)

[ 90 900 530]


In [ ]:
ikki=np.random.randint(1,100,size=(3,3))#2olchovli masiv yaratdik
print(ikki*10)

[[ 20 840 920]
 [600 710 440]
 [ 80 470 350]]


In [ ]:
uch=np.random.randint(1,50,size=(3,4,5))
print(uch)#3 olchovli massiv

[[[39 33  1 27 13]
  [41  3 39  6  8]
  [27  9 37 33 42]
  [44 24 15 32 32]]

 [[24 41 49 49 12]
  [39  2  3 49 37]
  [49 17 49  2  2]
  [28 23 37 32 33]]

 [[ 1 19  2 44 26]
  [32  6 32  4 11]
  [17 38 24  5 34]
  [ 6 22 11 48 16]]]


In [ ]:
list=[10,20,30,40,50,60,70,80,90,100]
tanlov=np.random.choice(list)
print(tanlov)

10


In [ ]:
#6ta soni tanlab beradi kritilgan raqmlar ichidan
list=[10,20,30,40,50,60,70,80,90,100]
koptanlov22=np.random.choice(list,size=3,replace=False)
print(koptanlov22)
#false sonlardi qayta qayta omedi
#true ikkita qlb oladi

[ 10  20 100]


In [ ]:
a=np.random.rand(12)
print(a)

[0.01658783 0.51209306 0.22649578 0.64517279 0.17436643 0.69093774
 0.38673535 0.93672999 0.13752094 0.34106635 0.11347352 0.92469362]


In [ ]:
np.random.seed(42)
d=np.random.rand(15)
print(d)
#seed=tasodifiy raqamdi qotirib beradi

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497]


In [ ]:
#suffle=aralashtirish
arr1=np.array([1,2,3,4,5,6,7,8,9])
np.random.shuffle(arr1)
print(arr1)

[6 3 8 7 9 2 4 1 5]
